// zip file signatures
export const LOCAL_FILE_HEADER_SIGNATURE = 0x04034b50;
export const CENTRAL_DIRECTORY_SIGNATURE = 0x02014b50;
export const END_OF_CENTRAL_DIRECTORY_SIGNATURE = 0x06054b50;
export const ZIP64_END_OF_CENTRAL_DIRECTORY_SIGNATURE = 0x06064b50;
export const ZIP64_END_OF_CENTRAL_DIRECTORY_LOCATOR_SIGNATURE = 0x07064b50;

// compression methods
export const COMPRESSION_STORED = 0;
export const COMPRESSION_DEFLATE = 8;

// field sizes
export const LOCAL_FILE_HEADER_SIZE = 30;
export const CENTRAL_DIRECTORY_HEADER_SIZE = 46;
export const END_OF_CENTRAL_DIRECTORY_SIZE = 22;
export const ZIP64_END_OF_CENTRAL_DIRECTORY_SIZE = 56;
export const ZIP64_END_OF_CENTRAL_DIRECTORY_LOCATOR_SIZE = 20;
